### ISSUE TITLE
ClassNotFoundException when running scanner from commandline

### ISSUE THREAD

**Issue by rgalang81** [SonarSource/sonar-scm-cvs#8]
I'm getting the exception below when I run the sonar-scanner.bat from the command line. When I disable the plugin on my sonarqube server the scan completes just fine. When I check the CVS plugin JAR it is missing these classes it needs. 

Creation of command 'Import' failed:
java.lang.ClassNotFoundException: org.netbeans.lib.cvsclient.commandLine.command.Import
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.netbeans.lib.cvsclient.commandLine.CommandFactory.createCommandProviders(CommandFactory.java:54)
	at org.netbeans.lib.cvsclient.commandLine.CommandFactory.<init>(CommandFactory.java:45)
	at org.netbeans.lib.cvsclient.commandLine.CommandFactory.getDefault(CommandFactory.java:74)
	at org.sonarqube.scm.cvs.CvsCommandExecutor.processCommand(CvsCommandExecutor.java:89)

Here's the full log from the scan. I'm running version 6.7.4 (build 38452). I used the plugin that was pulled in the marketplace page.
[https://file.io/J32dEv](url)

**Comment by henryju** [comment]
Thanks for the feedback. I think it was caused by https://github.com/SonarQubeCommunity/sonar-scm-cvs/pull/6/commits/34cae3adaec4d388650b5a75fb5dadf4d5722bbd

**Comment by henryju** [comment]
Can you try this artifact? https://github.com/SonarQubeCommunity/sonar-scm-cvs/releases/download/1.2-rc1/sonar-scm-cvs-plugin-1.2-SNAPSHOT.jar

**Comment by rgalang81** [comment]
thanks, tried that. no longer getting the ClassNotFoundException, but running into a new error. I'm not sure if this is my platform's issue or still related to the CVS APIs included with the plugin

`
06:09:39.954 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: The CVS annotate command [cvs -d :pserver:@cvs.lawson.com:/cvs/cvs_archive -t -z 3 -f -T C:\sandbox\tip10\LawsonPlatform\ui\workspace\portal\.scannerwork\.sonartmp\cvs annotate admin/admin-common.css] failed.

Stdout:





Stderr:
S-> Reader_Lock(/cvs/cvs_archive/LawsonPlatform/ui/workspace/portal/admin)
S-> Lock_Cleanup()
 

	at org.sonarqube.scm.cvs.CvsBlameCommand.blame(CvsBlameCommand.java:71)
	at org.sonar.scanner.scm.ScmPublisher.publish(ScmPublisher.java:85)
	at org.sonar.scanner.phases.PublishPhaseExecutor.afterSensors(PublishPhaseExecutor.java:60)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:90)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
`

**Comment by rgalang81** [comment]
The new error is specific to my server. Looks like it has one of those problems with dropping connections. I think we can consider this one closed by the sent over fix

**Comment by henryju** [comment]
Thanks for the confirmation
